title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          # Your name.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://muan.co
    external:     true
  - name:         Email
    url:          mailto:hello@muan.co
    external:     true
  - name:         GitHub
    url:          http://github.com/muan
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
